# Generated by Django 2.2.2 on 2019-07-06 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crequests', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='crequest',
            new_name='crequests',
        ),
    ]
