# Generated by Django 2.2.2 on 2019-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('dcode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
