# Generated by Django 3.0.8 on 2021-08-02 19:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tocode', models.CharField(max_length=10)),
                ('totype', models.CharField(max_length=1)),
                ('fromcode', models.CharField(max_length=10)),
                ('fromtype', models.CharField(max_length=1)),
                ('gstatus', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('msg', models.TextField()),
                ('dateandtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
