# Generated by Django 3.2.6 on 2021-09-17 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='dateandtime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
