# Generated by Django 2.2.2 on 2019-06-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20190624_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='fromtype',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='totype',
            field=models.CharField(max_length=1),
        ),
    ]
