# Generated by Django 3.2.6 on 2021-09-17 21:29

import django.core.validators
from django.db import migrations, models
import trainee.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trainee',
            fields=[
                ('rep_date', models.DateField(default='9999-12-31')),
                ('tcode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('fname', models.CharField(max_length=120)),
                ('mname', models.CharField(max_length=120)),
                ('dob', models.DateField(default='1970-01-01')),
                ('address', models.TextField(max_length=320)),
                ('mobile', models.BigIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(6666666666), django.core.validators.MaxValueValidator(9999999999)])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('institute', models.CharField(max_length=200)),
                ('qual', models.CharField(max_length=180)),
                ('dur', models.IntegerField(default='4', validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(12)])),
                ('dcode', models.CharField(blank=True, max_length=10, null=True)),
                ('mcode', models.CharField(blank=True, max_length=10, null=True)),
                ('gcode', models.CharField(blank=True, max_length=10, null=True)),
                ('proj', models.CharField(blank=True, max_length=200, null=True)),
                ('proj_assign_date', models.DateField(blank=True, default='9999-12-31', null=True)),
                ('proj_sub_date', models.DateField(blank=True, default='9999-12-31', null=True)),
                ('clearances', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=trainee.models.update_filename, validators=[trainee.models.validate_image])),
            ],
        ),
    ]
