# Generated by Django 2.2.2 on 2019-07-03 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0002_auto_20190702_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainee',
            name='dob',
            field=models.DateTimeField(default='1970-01-01'),
        ),
    ]
