# Generated by Django 2.2.2 on 2019-07-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_trainee_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='dob',
            field=models.DateField(default='1970-01-01'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='proj_assign_date',
            field=models.DateField(blank=True, default='9999-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='proj_sub_date',
            field=models.DateField(blank=True, default='9999-12-31', null=True),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='rep_date',
            field=models.DateField(default='9999-12-31'),
        ),
    ]
