# Generated by Django 2.2.2 on 2019-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=120)),
                ('dcode', models.CharField(max_length=10)),
                ('ccode', models.CharField(max_length=10)),
                ('mcode', models.CharField(max_length=10)),
            ],
        ),
    ]
