# Generated by Django 2.2.2 on 2019-07-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clearance',
            name='id',
        ),
        migrations.AlterField(
            model_name='clearance',
            name='ccode',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
