# Generated by Django 2.2.2 on 2019-06-19 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_auto_20190619_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencne',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
