# Generated by Django 2.2.2 on 2019-06-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_auto_20190619_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendencne',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterUniqueTogether(
            name='attendencne',
            unique_together={('tcode', 'datetime')},
        ),
    ]
