# Generated by Django 2.2.2 on 2019-06-30 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_auto_20190619_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencne',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterUniqueTogether(
            name='attendencne',
            unique_together={('tcode', 'date')},
        ),
    ]
