# Generated by Django 2.2.2 on 2019-06-30 18:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0006_auto_20190630_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcode', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
            ],
            options={
                'unique_together': {('tcode', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='attendencne',
        ),
    ]
