# Generated by Django 3.2.6 on 2021-09-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='group',
            fields=[
                ('gcode', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('dcode', models.CharField(max_length=10)),
                ('mcode', models.CharField(max_length=10)),
            ],
        ),
    ]
