# Generated by Django 2.2.2 on 2019-06-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groups',
            fields=[
                ('gcode', models.CharField(max_length=120, primary_key=True, serialize=False, unique=True)),
                ('dcode', models.CharField(max_length=10)),
                ('mcode', models.CharField(max_length=10)),
            ],
        ),
    ]
