# Generated by Django 2.2.2 on 2019-06-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='groups',
            new_name='group',
        ),
    ]
