# Generated by Django 2.2.2 on 2019-06-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20190618_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gcode',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
