# Generated by Django 3.0.8 on 2021-08-02 19:07

import django.core.validators
from django.db import migrations, models
import mentor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mentor',
            fields=[
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(max_length=120)),
                ('mobile', models.BigIntegerField(default=9999999999, unique=True, validators=[django.core.validators.MinValueValidator(6666666666), django.core.validators.MaxValueValidator(9999999999)])),
                ('co_ord', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('dcode', models.CharField(default=0, max_length=10)),
                ('mcode', models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=mentor.models.update_filename, validators=[mentor.models.validate_image])),
            ],
        ),
    ]
