# Generated by Django 2.2.2 on 2019-06-19 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='co_ord',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='mentor',
            name='mobile',
            field=models.BigIntegerField(default=9999999999, unique=True, validators=[django.core.validators.MinValueValidator(6666666666), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
