# Generated by Django 2.2.2 on 2019-06-27 12:11

from django.db import migrations, models
import mentor.models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20190620_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=mentor.models.update_filename, validators=[mentor.models.validate_image]),
        ),
    ]
