# Generated by Django 2.2.2 on 2019-07-02 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_mentor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='mcode',
            field=models.AutoField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
